import type { CountryConfig, CountrySlug } from "./types";

export const COUNTRIES: Record<CountrySlug, CountryConfig> = {
  ksa: {
    slug: "ksa",
    countries: ["SA"],
    name: { en: "Saudi Arabia", ar: "المملكة العربية السعودية" },
    defaultLocale: "ar",
    defaultCurrency: "SAR",
    stores: ["amazon-sa", "noon-sa", "jarir", "extra", "lulu-sa"],
    phonePrefix: "+966",
    flagEmoji: "🇸🇦",
  },
  eg: {
    slug: "eg",
    countries: ["EG"],
    name: { en: "Egypt", ar: "مصر" },
    defaultLocale: "ar",
    defaultCurrency: "EGP",
    stores: ["amazon-eg", "noon-eg", "jumia-eg", "btech", "2b"],
    phonePrefix: "+20",
    flagEmoji: "🇪🇬",
  },
  uae: {
    slug: "uae",
    countries: ["AE"],
    name: { en: "United Arab Emirates", ar: "الإمارات العربية المتحدة" },
    defaultLocale: "ar",
    defaultCurrency: "AED",
    stores: ["amazon-ae", "noon-ae", "sharaf-dg", "carrefour-ae"],
    phonePrefix: "+971",
    flagEmoji: "🇦🇪",
  },
  all: {
    slug: "all",
    countries: ["SA", "EG", "AE", "KW"],
    name: { en: "Middle East", ar: "الشرق الأوسط" },
    defaultLocale: "ar",
    defaultCurrency: "USD",
    stores: [
      "amazon-sa",
      "amazon-eg",
      "amazon-ae",
      "noon-sa",
      "noon-eg",
      "noon-ae",
      "jarir",
      "extra",
      "jumia-eg",
      "btech",
      "2b",
      "sharaf-dg",
      "carrefour-ae",
      "lulu-sa",
    ],
    phonePrefix: "+966",
    flagEmoji: "🌍",
  },
};
