import type { VerticalConfig, VerticalSlug } from "./types";

export const VERTICALS: Record<VerticalSlug, VerticalConfig> = {
  general: {
    slug: "general",
    name: { en: "All Products", ar: "كل المنتجات" },
    tagline: {
      en: "Compare prices across 14 stores in real time",
      ar: "قارن الأسعار عبر 14 متجر في الوقت الفعلي",
    },
    categories: [
      "electronics",
      "fashion",
      "home",
      "grocery",
      "pharma",
      "beauty",
      "sports",
      "toys",
    ],
    primaryColor: "#0066cc",
    accentColor: "#ff9900",
    defaultStores: [
      "amazon-sa",
      "amazon-eg",
      "amazon-ae",
      "noon-sa",
      "noon-eg",
      "noon-ae",
      "jarir",
      "extra",
      "jumia-eg",
      "btech",
      "2b",
      "sharaf-dg",
      "carrefour-ae",
      "lulu-sa",
    ],
    heroEmoji: "🛒",
  },
  electronics: {
    slug: "electronics",
    name: { en: "Electronics", ar: "الإلكترونيات" },
    tagline: {
      en: "Never overpay for tech again — instant price comparison across major electronics retailers",
      ar: "لا تدفع المزيد للتكنولوجيا — مقارنة فورية للأسعار عبر متاجر الإلكترونيات الكبرى",
    },
    categories: [
      "phones",
      "laptops",
      "tablets",
      "tvs",
      "headphones",
      "wearables",
      "gaming",
      "cameras",
      "monitors",
      "accessories",
      "home-appliances",
    ],
    primaryColor: "#1e40af",
    accentColor: "#06b6d4",
    defaultStores: [
      "amazon-sa",
      "amazon-eg",
      "amazon-ae",
      "noon-sa",
      "noon-eg",
      "noon-ae",
      "jarir",
      "extra",
      "btech",
      "2b",
      "sharaf-dg",
    ],
    heroEmoji: "📱",
  },
  fashion: {
    slug: "fashion",
    name: { en: "Fashion", ar: "الأزياء" },
    tagline: {
      en: "Discover the best fashion deals across the region's top retailers",
      ar: "اكتشف أفضل عروض الأزياء عبر أكبر متاجر المنطقة",
    },
    categories: [
      "womens-clothing",
      "mens-clothing",
      "kids",
      "shoes",
      "bags",
      "accessories",
      "watches",
      "jewelry",
      "perfumes",
      "abayas",
    ],
    primaryColor: "#be185d",
    accentColor: "#f59e0b",
    defaultStores: [
      "amazon-sa",
      "amazon-eg",
      "amazon-ae",
      "noon-sa",
      "noon-eg",
      "noon-ae",
      "jumia-eg",
    ],
    heroEmoji: "👗",
  },
  grocery: {
    slug: "grocery",
    name: { en: "Grocery & Daily", ar: "البقالة والأساسيات" },
    tagline: {
      en: "Save on every grocery run — compare hypermarket prices at a glance",
      ar: "وفّر في كل تسوّق — قارن أسعار الهايبرماركت في لحظة",
    },
    categories: [
      "fresh-produce",
      "dairy",
      "pantry",
      "beverages",
      "snacks",
      "frozen",
      "household",
      "baby-care",
      "pet-supplies",
    ],
    primaryColor: "#15803d",
    accentColor: "#facc15",
    defaultStores: [
      "carrefour-ae",
      "lulu-sa",
      "amazon-sa",
      "amazon-ae",
      "noon-sa",
      "noon-ae",
    ],
    heroEmoji: "🛒",
  },
  pharma: {
    slug: "pharma",
    name: { en: "Pharmacy & Health", ar: "الصيدلية والصحة" },
    tagline: {
      en: "Compare medicine, vitamins, and personal-care prices across trusted pharmacies",
      ar: "قارن أسعار الأدوية والفيتامينات ومستلزمات العناية الشخصية من صيدليات موثوقة",
    },
    categories: [
      "otc-medicine",
      "vitamins",
      "supplements",
      "personal-care",
      "baby-care",
      "first-aid",
      "skincare",
      "sexual-health",
      "medical-devices",
    ],
    primaryColor: "#0e7490",
    accentColor: "#22c55e",
    defaultStores: ["amazon-sa", "amazon-eg", "amazon-ae", "noon-sa", "noon-eg"],
    heroEmoji: "💊",
  },
};
